config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :lists do
    resources :bookmarks, only: [:new, :create, :delete]
  end
  get 'lists', to: 'lists#index'
  get 'lists/:id', to: 'lists#show'
  get 'lists/new', to: 'lists#new'
  post 'lists', to: 'lists#create'
  root to: 'lists#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks
  # before_destroy :checks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new # Needed to instantiate the form_with
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    # redirect_to lists_path(@list)
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  private

  def list_params
    params.require(:list).permit(:name, :movie_id, :bookmark_ids)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class='title'>
<h1> Welcome to your movie lists</h1>
</div>
<div>
<p class="btn btn-info btn-lg"> <%= link_to "<button>Create a movie list</button>".html_safe, lists_new_path %> </p>
</div>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<div>
<h1> Make a new list </h1>

<%= simple_form_for @list do |f| %>
    <%= f.input :name %>
  <%= f.association :movies %>
  <%= f.association :bookmarks %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/lists/show.html.erb
<h1> Lists details</h2>
<h2><%= @list.name %></h2>
<p class="btn btn-success btn-lg"> <%= link_to "<button>Back to Lists</button>".html_safe, lists_path %> </p>
<p><strong>movies</strong></p>
<ul>
  <% @list.movies.each do |movie| %>
    <li><%= movie.title %></li>
  <% end %>
</ul>
<br>

<%# <p class="btn btn-info btn-lg"> <%= link_to "<button>Add a bookmark</button>".html_safe, new_list_bookmark_path %>